### PR TITLE
Retry sessions

### LINKED ISSUE #996: Implement session-level retry
When performing a test run with multiple browser sessions, such as Intern's own CI tests, one or two browsers may sporadically fail while the others succeed, leading to a failure of the overall test run. In that situation (where only some browser sessions fail), Intern could automatically re-run the failing browser sessions at least once in case the failure was a fluke.

This is similar to #340, but at the session level rather than the individual test level.

### PR DESCRIPTION
**Pull request by devpaul**
Resolves #996

### CODE REVIEW

File: src/lib/Suite.ts [hunk 1]
```diff
@@ -213,6 +213,15 @@ export default class Suite implements SuiteProperties {
...
   }
 
+  get failed(): boolean {
+    return this.tests.some(suiteOrTest => {
+      return (
+        !!this.error ||
+        (isSuite(suiteOrTest) ? suiteOrTest.failed : suiteOrTest.error)
+      );
+    });
+  }
```
Comment (jason0x43) [inline src/lib/Suite.ts]: Could this just be `return this.numFailedTests > 0 || this.error`?

File: src/lib/common/config.ts [hunk 2]
```diff
@@ -199,6 +199,9 @@ export interface Config extends ResourceConfig {
   /** Whether to collect coverage data from functional tests */
   functionalCoverage: boolean;
 
+  /** The number of times to rerun a session when a session fails when another one succeeds */
```
Comment (jason0x43) [inline src/lib/common/config.ts]: Maybe "when it fails and at least one other session succeeds"

File: src/lib/executors/Node.ts [hunk 3]
```diff
@@ -875,13 +876,34 @@ export default class Node extends Executor<NodeEvents, Config, NodePlugins> {
...
-              () => (testTask = this._runRemoteTests())
-            );
+
+            let remainingAttempts = 1 + (this.config.functionalRetries || 0);
+            let suites = this._sessionSuites;
+
+            await this._loadFunctionalSuites();
+            while (remainingAttempts && suites.length) {
+              remainingAttempts--;
+              if (suites.length !== this._sessionSuites!.length) {
```
Comment (jason0x43) [inline src/lib/executors/Node.ts]: It seems odd that `this._sessionSuites` needs a `!` but `suites` doesn't.  Consider adding `const sessionSuites = this._sessionSuites!` and using that to avoid having a bunch of non-null assertions.

File: src/lib/executors/Node.ts [hunk 4]
```diff
@@ -875,13 +876,34 @@ export default class Node extends Executor<NodeEvents, Config, NodePlugins> {
...
+                this.log(
+                  'reattempting',
+                  suites.length,
+                  'of',
+                  this._sessionSuites!.length,
+                  'environments'
+                );
+              }
+              testTask = this._runRemoteTests(suites);
+              await testTask.catch(remainingAttempts ? () => {} : undefined);
```
Comment (jason0x43) [inline src/lib/executors/Node.ts]: Why not a `try/catch`?

File: src/lib/executors/Node.ts [hunk 5]
```diff
@@ -875,13 +876,34 @@ export default class Node extends Executor<NodeEvents, Config, NodePlugins> {
...
+              suites = suites.filter(suite => suite.failed);
```
Comment (jason0x43) [inline src/lib/executors/Node.ts]: Consider using a meaningful name here (maybe `failingSuites`), just to make it clearer what's being done in the following if statement, then assign that to `suites` at the end of the loop.

**Review by jason0x43 — CHANGES_REQUESTED** [review]
This looks good overall. I just had a few cleanup suggestions, and the `Suite.failed` method could probably be simplified.

File: src/lib/executors/Node.ts (hunk 4 above)
Comment (devpaul) [reply src/lib/executors/Node.ts]: This seemed less verbose than

File: src/lib/executors/Node.ts (hunk 3 above)
Comment (devpaul) [reply src/lib/executors/Node.ts]: It doesn't need the `!` any longer. Removed.

File: src/lib/executors/Node.ts (hunk 5 above)
Comment (devpaul) [reply src/lib/executors/Node.ts]: Hmm... The conditional check is on the next line. Do you think it needs an explicit name when usage is so close to assignment?

Comment (jason0x43) [reply src/lib/executors/Node.ts]: It makes it read better. It was the usage specifically that prompted the comment; it's not immediately apparent when skimming through the code that `if (suites.length === this._sessionSuites.length)` is comparing a list of failing suites to the original list.

File: src/lib/executors/Node.ts (hunk 4 above)
Comment (jason0x43) [reply src/lib/executors/Node.ts]: I think we should be more explicit in general; `catch(remainingAttempts ? () => {} : undefined)` obscures the fact that the goal is to consume or throw the error. If you expand the catch, it's not much different than the `try / catch`, so we should probably use that for consistency.

**Comment by jason0x43** [comment]
The `config.json` schema and the docs should also be updated for the new config parameter.

File: src/lib/Suite.ts [hunk 6]
```diff
@@ -346,6 +346,16 @@ export default class Suite implements SuiteProperties {
     );
   }
 
+  /**
+   * Explicity reset the suite so it may run again
+   */
+  reset() {
+    this._remote = undefined;
+    // Remove implicit reset from run() (in case it's relied upon)
```
Comment (jason0x43) [inline src/lib/Suite.ts]: Since this is going in v5, go ahead and actually remove the implicit reset code from Suite. Move the TODO about canceling suite runs here.

File: src/lib/executors/Node.ts [hunk 7]
```diff
@@ -875,13 +876,46 @@ export default class Node extends Executor<NodeEvents, Config, NodePlugins> {
...
+            const allSessions = this._sessionSuites;
+            let suites = allSessions;
+            let remainingAttempts = 1 + (this.config.functionalRetries || 0);
+
+            await this._loadFunctionalSuites();
+            while (remainingAttempts && suites.length) {
+              remainingAttempts--;
+              if (suites.length !== allSessions.length) {
+                this.log(
+                  'reattempting',
```
Comment (jason0x43) [inline src/lib/executors/Node.ts]: We ideally shouldn't say 'reattempting' on the first run.

File: src/lib/executors/Node.ts [hunk 8]
```diff
@@ -875,13 +876,46 @@ export default class Node extends Executor<NodeEvents, Config, NodePlugins> {
...
+                );
+              }
+              try {
+                testTask = this._runRemoteTests(suites);
+                await testTask;
+              } catch (e) {
+                this.log(`suite error: ${e}`);
+                // recover from exceptions to allow for retries
+              }
+              const failedSuites = (suites = suites.filter(suite =>
```
Comment (jason0x43) [inline src/lib/executors/Node.ts]: The filter statement can just be `suites.filter(isFailedSuite)`

File: src/lib/executors/Node.ts [hunk 9]
```diff
@@ -875,13 +876,46 @@ export default class Node extends Executor<NodeEvents, Config, NodePlugins> {
...
+          .then(async () => {
             if (!this._sessionSuites) {
               return;
             }
-            return this._loadFunctionalSuites().then(
-              () => (testTask = this._runRemoteTests())
-            );
+
+            const allSessions = this._sessionSuites;
+            let suites = allSessions;
```
Comment (jason0x43) [inline src/lib/executors/Node.ts]: Could we call this `sessions`, and have `failedSessions`? The naming scheme is a bit inconsistent between here and `_runRemoteTests`.

**Review by jason0x43 — CHANGES_REQUESTED** [review]
Just a couple more changes (it was going to need some rework before the merge, anyway 😄)

File: src/lib/executors/Node.ts (hunk 7 above)
Comment (devpaul) [reply src/lib/executors/Node.ts]: suites.length and allSessions.length will be equal on the first run. Suites are filtered later as successful ones are removed.

Comment (jason0x43) [reply src/lib/executors/Node.ts]: Ah, good point

**Review by jason0x43 — APPROVED** [review]
